name: draf
channels:
  - conda-forge
dependencies:  # NOTE: here '=' (single)
  - ephem  # dependency of gsee_module
  - geopy
  - glpk
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - pvlib-python >= 0.6.3  # dependency of gsee_module
  - pyomo
  - python
  - seaborn
  - pip:  # NOTE: here '==' (double)
    - elmada
    - holidays
    - '--editable=.[dev,jupyter]'  # installs a full editable version of draf
