name: draf
channels:
  - conda-forge
  - gurobi
  - plotly
dependencies:
  - gurobi
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - pyomo>=5.7
  - python=3.7  # gurobi has problems with python >3.7
  - seaborn
  - pip:
    - holidays
    - elmada
    - '--editable=.'  # installs an editable version of draf