name: draf
channels:
  - conda-forge
  - plotly
dependencies:  # NOTE: here '=' (single)
  - ipython
  - ipywidgets
  - jupyter
  - jupytext
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - pyomo>=5.7
  - python=3.7
  - seaborn
  - pip:  # NOTE: here '==' (double)
    - holidays
    - elmada
    - '--editable=.[dev,jupyter]'  # installs a full editable version of draf