[tool.black]
line-length = 100
exclude = '''
/(
    \.eggs
  | \.git
  | \.github
  | \.mypy_cache
  | \.pytest_cache
  | \.vscode
  | .*\.egg-info
  | doc
  | local
)/
'''

[tool.isort]
line_length = 100
include_trailing_comma = true
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "--strict-markers",
    "--cov=draf",
    # "--cov-report=term:skip-covered",
    # "--cov-report=html",
    "--durations=3",
    # "-m=not slow",
    "--disable-pytest-warnings",
]
markers = [
  "slow: marks slow tests > 1sec and not an important model test"
]
python_files = "test_*.py"
python_functions = "test_*"
testpaths = ["tests"]

# [tool.coverage.run]
# omit = []