[tool.black]
line-length = 100
exclude = '''
/(
    \.eggs
  | \.git
  | \.github
  | \.mypy_cache
  | \.pytest_cache
  | \.vscode
  | .*\.egg-info
  # directories without python source files
  | doc
  | local
  # different line length `black --line-length=120 draf/models`
  | draf/models
)/
'''

[tool.isort]
line_length = 100
include_trailing_comma = true
profile = "black"
