GRB_OPT_STATUS = {
    1: "LOADED",
    2: "OPTIMAL",
    3: "INFEASIBLE",
    4: "INF_OR_UNBD",
    5: "UNBOUNDED",
    6: "CUTOFF",
    7: "ITERATION_LIMIT",
    8: "NODE_LIMIT",
    9: "TIME_LIMIT",
    10: "SOLUTION_LIMIT",
    11: "INTERRUPTED",
    12: "NUMERIC",
    13: "SUBOPTIMAL",
    14: "INPROGRESS",
    15: "USER_OBJ_LIMIT",
}

VAR_PAR = {
    "p": "par_dic",
    "par": "par_dic",
    "params": "par_dic",
    "v": "res_dic",
    "var": "res_dic",
    "vars": "res_dic",
    "variables": "res_dic",
    "r": "res_dic",
    "res": "res_dic",
    "results": "res_dic",
}
